name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
  schedule:
    - cron: '15/30 * * * *'

jobs:
  check-ip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python test.py

